name: projeto_leite
description: Backend para o sistema de gestÃ£o de produtores de leite
version: 1.0.0

environment:
  sdk: ^3.8.3

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
